// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CommunicationType string

const (
	CommunicationTypeEmail   CommunicationType = "email"
	CommunicationTypePhone   CommunicationType = "phone"
	CommunicationTypeMeeting CommunicationType = "meeting"
	CommunicationTypeOther   CommunicationType = "other"
)

func (e *CommunicationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommunicationType(s)
	case string:
		*e = CommunicationType(s)
	default:
		return fmt.Errorf("unsupported scan type for CommunicationType: %T", src)
	}
	return nil
}

type NullCommunicationType struct {
	CommunicationType CommunicationType `json:"communication_type"`
	Valid             bool              `json:"valid"` // Valid is true if CommunicationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommunicationType) Scan(value interface{}) error {
	if value == nil {
		ns.CommunicationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommunicationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommunicationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommunicationType), nil
}

type EventStatus string

const (
	EventStatusInquiry     EventStatus = "inquiry"
	EventStatusPlanning    EventStatus = "planning"
	EventStatusPreparation EventStatus = "preparation"
	EventStatusInProgress  EventStatus = "in_progress"
	EventStatusCompleted   EventStatus = "completed"
	EventStatusFollowUp    EventStatus = "follow_up"
)

func (e *EventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventStatus(s)
	case string:
		*e = EventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventStatus: %T", src)
	}
	return nil
}

type NullEventStatus struct {
	EventStatus EventStatus `json:"event_status"`
	Valid       bool        `json:"valid"` // Valid is true if EventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventStatus), nil
}

type ResourceType string

const (
	ResourceTypeStaff     ResourceType = "staff"
	ResourceTypeEquipment ResourceType = "equipment"
	ResourceTypeMaterials ResourceType = "materials"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType `json:"resource_type"`
	Valid        bool         `json:"valid"` // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type TaskCategory string

const (
	TaskCategoryPreEvent    TaskCategory = "pre_event"
	TaskCategoryDuringEvent TaskCategory = "during_event"
	TaskCategoryPostEvent   TaskCategory = "post_event"
)

func (e *TaskCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskCategory(s)
	case string:
		*e = TaskCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskCategory: %T", src)
	}
	return nil
}

type NullTaskCategory struct {
	TaskCategory TaskCategory `json:"task_category"`
	Valid        bool         `json:"valid"` // Valid is true if TaskCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TaskCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskCategory), nil
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusCompleted  TaskStatus = "completed"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type UserRole string

const (
	UserRoleAdministrator UserRole = "administrator"
	UserRoleManager       UserRole = "manager"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ArchivedEvent struct {
	ID                 int32          `json:"id"`
	ClientID           int32          `json:"client_id"`
	EventName          string         `json:"event_name"`
	EventDate          time.Time      `json:"event_date"`
	Location           sql.NullString `json:"location"`
	Status             EventStatus    `json:"status"`
	EstimatedAttendees sql.NullInt32  `json:"estimated_attendees"`
	Notes              sql.NullString `json:"notes"`
	IsArchived         bool           `json:"is_archived"`
	ArchivedAt         sql.NullTime   `json:"archived_at"`
	ArchivedBy         sql.NullInt32  `json:"archived_by"`
	CreatedBy          int32          `json:"created_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CompanyName        string         `json:"company_name"`
	ContactName        string         `json:"contact_name"`
	ArchivedByName     sql.NullString `json:"archived_by_name"`
}

type Client struct {
	ID          int32          `json:"id"`
	CompanyName string         `json:"company_name"`
	ContactName string         `json:"contact_name"`
	Email       string         `json:"email"`
	Phone       sql.NullString `json:"phone"`
	Address     sql.NullString `json:"address"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Event struct {
	ID                 int32          `json:"id"`
	ClientID           int32          `json:"client_id"`
	EventName          string         `json:"event_name"`
	EventDate          time.Time      `json:"event_date"`
	Location           sql.NullString `json:"location"`
	Status             EventStatus    `json:"status"`
	EstimatedAttendees sql.NullInt32  `json:"estimated_attendees"`
	Notes              sql.NullString `json:"notes"`
	IsArchived         bool           `json:"is_archived"`
	ArchivedAt         sql.NullTime   `json:"archived_at"`
	ArchivedBy         sql.NullInt32  `json:"archived_by"`
	CreatedBy          int32          `json:"created_by"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type EventStatusLog struct {
	ID        int32           `json:"id"`
	EventID   int32           `json:"event_id"`
	OldStatus NullEventStatus `json:"old_status"`
	NewStatus EventStatus     `json:"new_status"`
	ChangedBy int32           `json:"changed_by"`
	Notes     sql.NullString  `json:"notes"`
	ChangedAt time.Time       `json:"changed_at"`
}

type Resource struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Type        ResourceType   `json:"type"`
	HourlyRate  sql.NullString `json:"hourly_rate"`
	IsAvailable bool           `json:"is_available"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ResourceSchedule struct {
	ID         int32          `json:"id"`
	ResourceID int32          `json:"resource_id"`
	EventID    int32          `json:"event_id"`
	TaskID     sql.NullInt32  `json:"task_id"`
	StartTime  time.Time      `json:"start_time"`
	EndTime    time.Time      `json:"end_time"`
	Notes      sql.NullString `json:"notes"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Task struct {
	ID              int32          `json:"id"`
	EventID         int32          `json:"event_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Category        TaskCategory   `json:"category"`
	Status          TaskStatus     `json:"status"`
	AssignedTo      sql.NullInt32  `json:"assigned_to"`
	DueDate         sql.NullTime   `json:"due_date"`
	DependsOnTaskID sql.NullInt32  `json:"depends_on_task_id"`
	IsOverdue       bool           `json:"is_overdue"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type TaskResource struct {
	TaskID     int32     `json:"task_id"`
	ResourceID int32     `json:"resource_id"`
	AssignedAt time.Time `json:"assigned_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Role         UserRole  `json:"role"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
