// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Find all existing schedule entries that overlap with the requested time range
	// for any of the specified resources
	CheckConflicts(ctx context.Context, arg CheckConflictsParams) ([]CheckConflictsRow, error)
	CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (ResourceSchedule, error)
	DeleteScheduleEntriesByTask(ctx context.Context, taskID sql.NullInt32) error
	DeleteScheduleEntry(ctx context.Context, id int32) error
	GetResourceByID(ctx context.Context, id int32) (Resource, error)
	GetResourceSchedule(ctx context.Context, arg GetResourceScheduleParams) ([]GetResourceScheduleRow, error)
	GetScheduleEntryByID(ctx context.Context, id int32) (GetScheduleEntryByIDRow, error)
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
}

var _ Querier = (*Queries)(nil)
