import {
  boolean,
  index,
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
} from 'drizzle-orm/pg-core';
import { events } from './events';
import { menuItems } from './menu-items';
import { users } from './users';
import { venues } from './venues';

export const stationTypeEnum = pgEnum('station_type', [
  'oven',
  'grill',
  'prep_counter',
  'cold_storage',
  'stovetop',
  'fryer',
  'mixer',
]);

export const prepTypeEnum = pgEnum('prep_type', [
  'marinate',
  'bake',
  'grill',
  'plate',
  'chop',
  'mix',
  'chill',
  'fry',
  'assemble',
  'garnish',
]);

export const productionTaskStatusEnum = pgEnum('production_task_status', [
  'pending',
  'in_progress',
  'completed',
  'skipped',
]);

export const kitchenStations = pgTable(
  'kitchen_stations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name', { length: 255 }).notNull(),
    type: stationTypeEnum('type').notNull(),
    capacity: integer('capacity').default(1).notNull(),
    venueId: integer('venue_id').references(() => venues.id, { onDelete: 'set null' }),
    notes: text('notes'),
    isActive: boolean('is_active').default(true).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    typeIdx: index('idx_kitchen_stations_type').on(table.type),
    venueIdIdx: index('idx_kitchen_stations_venue_id').on(table.venueId),
    isActiveIdx: index('idx_kitchen_stations_is_active').on(table.isActive),
  })
);

/**
 * Production step template shape stored as JSONB on menu_items.
 * Each step maps to a production task when auto-generated.
 */
export type ProductionStepTemplate = {
  name: string;
  prepType: string;
  stationType: string;
  durationMinutes: number;
  offsetMinutes: number;
};

export const productionTasks = pgTable(
  'production_tasks',
  {
    id: serial('id').primaryKey(),
    eventId: integer('event_id')
      .references(() => events.id, { onDelete: 'cascade' })
      .notNull(),
    menuItemId: integer('menu_item_id').references(() => menuItems.id, {
      onDelete: 'set null',
    }),
    stationId: integer('station_id').references(() => kitchenStations.id, {
      onDelete: 'set null',
    }),
    name: varchar('name', { length: 255 }).notNull(),
    prepType: prepTypeEnum('prep_type').notNull(),
    durationMinutes: integer('duration_minutes').notNull(),
    offsetMinutes: integer('offset_minutes').notNull(),
    scheduledStart: timestamp('scheduled_start', { withTimezone: true }),
    scheduledEnd: timestamp('scheduled_end', { withTimezone: true }),
    status: productionTaskStatusEnum('status').default('pending').notNull(),
    servings: integer('servings'),
    assignedTo: integer('assigned_to').references(() => users.id, {
      onDelete: 'set null',
    }),
    dependsOnTaskId: integer('depends_on_task_id'),
    notes: text('notes'),
    isAutoGenerated: boolean('is_auto_generated').default(false).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    eventIdIdx: index('idx_production_tasks_event_id').on(table.eventId),
    menuItemIdIdx: index('idx_production_tasks_menu_item_id').on(table.menuItemId),
    stationIdIdx: index('idx_production_tasks_station_id').on(table.stationId),
    statusIdx: index('idx_production_tasks_status').on(table.status),
    scheduledStartIdx: index('idx_production_tasks_scheduled_start').on(table.scheduledStart),
    stationTimeIdx: index('idx_production_tasks_station_time').on(
      table.stationId,
      table.scheduledStart,
      table.scheduledEnd
    ),
  })
);
